import {chromium} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const origin=process.env.TEST_ORIGIN??'http://localhost:3000';
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('artifacts',{recursive:true});
await page.goto(origin);await page.getByRole('heading',{name:'ตลาดมีเรื่องให้รู้ทุกวัน ค่อย ๆ เข้าใจไปด้วยกัน'}).waitFor();
await page.getByRole('tab',{name:'ตัวเลขบอกอะไรเพิ่ม?'}).click();
await page.getByRole('heading',{name:'ดูราคา คู่กับปริมาณซื้อขาย'}).waitFor();
await page.getByRole('tab',{name:'ตัวเลขบอกอะไรเพิ่ม?'}).press('ArrowRight');
assert.equal(await page.getByRole('tab',{name:'แล้วควรจับตาอะไร?'}).getAttribute('aria-selected'),'true');
await page.screenshot({path:'artifacts/crypto-desktop.png',fullPage:true});
let result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa']).analyze();assert.deepEqual(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);
await page.setViewportSize({width:390,height:844});await page.goto(origin);await page.getByRole('tab',{name:'ข่าวกำลังเล่าอะไร?'}).waitFor();
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile horizontal overflow');
await page.screenshot({path:'artifacts/crypto-mobile.png',fullPage:true});
await page.goto(origin+'/register');await page.getByRole('heading',{name:'เริ่มเข้าใจตลาดไปด้วยกัน'}).waitFor();await page.getByLabel('ชื่อที่แสดง',{exact:true}).fill('ผู้ใช้ทดสอบ');await page.locator('input[name=password]').fill('a long example password');await page.getByRole('button',{name:'แสดงรหัสผ่าน',exact:true}).click();assert.equal(await page.locator('input[name=password]').getAttribute('type'),'text');
result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa']).analyze();assert.deepEqual(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);
await page.screenshot({path:'artifacts/crypto-register.png',fullPage:true});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: desktop, mobile, story tabs, registration, accessibility');
