import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID, createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { createPlatform } from './platform.js';
import { digest } from './security.js';
import { oauthActor } from './mcp-oauth.js';
import { Hono } from 'hono';
import { loginDestination } from './auth.js';
test('login return is restricted to local MCP consent, never an external redirect', async () => {
  const app = new Hono();
  app.get('/', c => c.json({ next: loginDestination(c, { origin: 'https://polylove.example' }) }));
  for (const value of ['https://evil.example', '//evil.example', '/app', '/oauth/authorize/../other', '/oauth/authorize?client_id=test']) {
    const r = await app.request('/', { headers: { cookie: 'mcp_return=' + encodeURIComponent(value) } });
    assert.equal((await r.json()).next, value === '/oauth/authorize?client_id=test' ? value : '/app');
    assert.match(r.headers.get('set-cookie'), /Max-Age=0/);
  }
});
test('OAuth requires admin consent, exact callback, PKCE and single-use code; revoke removes access', async t => {
  const db = new PGlite(); t.after(() => db.close());
  await db.exec(await readFile(new URL('./schema.sql', import.meta.url), 'utf8'));
  const actor = randomUUID();
  await db.query("INSERT INTO users(id,email,name,role,email_verified_at) VALUES($1,'oauth@test.example','Admin','admin',now())", [actor]);
  await db.query("INSERT INTO sessions(hash,user_id,expires_at) VALUES($1,$2,now()+interval '1 day')", [digest('session'), actor]);
  const config = { origin: 'https://polylove.example', mcpClientId: 'test-client', mcpRedirectUri: 'https://client.example/callback' };
  const app = createPlatform({ db, config }), verifier = 'v'.repeat(43);
  const p = { client_id: config.mcpClientId, redirect_uri: config.mcpRedirectUri, resource: config.origin + '/mcp', scope: 'market:read analysis:draft', response_type: 'code', code_challenge_method: 'S256', code_challenge: createHash('sha256').update(verifier).digest('base64url'), state: 'test-state' };
  const authorize = values => app.request('/oauth/authorize?' + new URLSearchParams(values), { headers: { cookie: 'session=session' } });
  const loggedOut = await app.request('/oauth/authorize?' + new URLSearchParams(p));
  assert.equal(loggedOut.status, 302);
  assert.equal(loggedOut.headers.get('location'), '/login');
  assert.match(loggedOut.headers.get('set-cookie'), /HttpOnly/);
  assert.equal((await authorize({ ...p, redirect_uri: 'https://evil.example' })).status, 400);
  const consent = await authorize(p); assert.equal(consent.status, 200);
  assert.equal((await db.query('SELECT code_hash FROM mcp_oauth_requests')).rows[0].code_hash, null);
  const id = (await consent.text()).match(/name="request_id" value="([^"]+)"/)[1];
  const post = (path, values, origin = config.origin) => app.request(path, { method: 'POST', headers: { cookie: 'session=session', origin, 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams(values).toString() });
  assert.equal((await post('/oauth/authorize', { request_id: id, decision: 'allow' }, 'https://evil.example')).status, 403);
  const approved = await post('/oauth/authorize', { request_id: id, decision: 'allow' });
  assert.equal(approved.status, 303);
  const redirect = new URL(approved.headers.get('location')); assert.equal(redirect.searchParams.get('state'), 'test-state');
  const exchange = { client_id: p.client_id, redirect_uri: p.redirect_uri, resource: p.resource, grant_type: 'authorization_code', code: redirect.searchParams.get('code'), code_verifier: verifier };
  assert.equal((await post('/oauth/token', { ...exchange, code_verifier: 'x'.repeat(43) })).status, 400);
  const response = await post('/oauth/token', exchange); assert.equal(response.status, 200);
  const token = (await response.json()).access_token;
  assert.equal(await oauthActor(db, token, config), actor);
  const status = await app.request('/api/v1/admin/mcp', { headers: { cookie: 'session=session' } });
  const data = await status.json();
  assert.equal(data.connections[0].active_tokens, 1);
  assert.ok(!JSON.stringify(data).includes(token));
  assert.ok(!JSON.stringify(data).includes(digest(token)));
  assert.equal((await app.request('/api/v1/admin/mcp')).status, 401);
  const other = randomUUID();
  await db.query("INSERT INTO users(id,email,name,role,email_verified_at) VALUES($1,'other@test.example','Other','admin',now())", [other]);
  await db.query("INSERT INTO sessions(hash,user_id,expires_at) VALUES($1,$2,now()+interval '1 day')", [digest('other-session'), other]);
  await db.query("INSERT INTO mcp_oauth_tokens(hash,actor,session_hash,client_id,resource,scope,expires_at) VALUES($1,$2,$3,$4,$5,$6,now()+interval '1 hour')", [digest('other-token'), other, digest('other-session'), p.client_id, p.resource, p.scope]);
  const revoked = await app.request('/api/v1/admin/mcp/revoke', { method: 'POST', headers: { origin: config.origin, cookie: 'session=session', 'content-type': 'application/json' }, body: '{}' });
  assert.equal(revoked.status, 200);
  assert.equal(await oauthActor(db, token, config), undefined);
  assert.equal(await oauthActor(db, 'other-token', config), other);
  assert.equal((await post('/oauth/token', exchange)).status, 400);
  assert.equal((await post('/oauth/revoke', { client_id: p.client_id, token })).status, 200);
  assert.equal(await oauthActor(db, token, config), undefined);
});
